### ISSUE TITLE
Rendering issue while using scientific notation of numbers inside SLD filters

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geoserver#202]
@aaime In some cases the numbers values inside filter of GeoCSS are translated in scientific notation when converted in SLD.

eg:
```css
[POP_EST >= 275860666.2]
[POP_EST < 551721192.4]
```

```xml
<ogc:Filter>
    <ogc:And>
        <ogc:PropertyIsGreaterThanOrEqualTo>
            <ogc:PropertyName>POP_EST</ogc:PropertyName>
            <ogc:Literal>2.758606662E8</ogc:Literal>
        </ogc:PropertyIsGreaterThanOrEqualTo>
        <ogc:PropertyIsLessThan>
            <ogc:PropertyName>POP_EST</ogc:PropertyName>
            <ogc:Literal>5.517211924E8</ogc:Literal>
        </ogc:PropertyIsLessThan>
    </ogc:And>
</ogc:Filter>
```

This generates some issue in the rendered map

current result:
missing India and China
![image](https://user-images.githubusercontent.com/19175505/92118152-60344f00-edf6-11ea-87c9-922565d77242.png)

expected result:
generated with an equivalent SLD style without the scientific notation
![image](https://user-images.githubusercontent.com/19175505/92118224-780bd300-edf6-11ea-927f-dedabb532715.png)

These are the data to replicate this issue:

- layer: https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip

- GeoCSS style:
```css
@mode 'Flat';
@styleTitle 'Fill';

/* @title >= 140 and < 275860666.2 */
[POP_EST >= 140]
[POP_EST < 275860666.2] {
  fill: #FFF7EC;
  fill-opacity: 1;
  stroke: #777777;
  stroke-width: 1;
}
/* @title >= 275860666.2 and < 551721192.4 */
[POP_EST >= 275860666.2]
[POP_EST < 551721192.4] {
  fill: #FDD49E;
  fill-opacity: 1;
  stroke: #777777;
  stroke-width: 1;
}
/* @title >= 551721192.4 and < 827581718.6 */
[POP_EST >= 551721192.4]
[POP_EST < 827581718.6] {
  fill: #FC8D59;
  fill-opacity: 1;
  stroke: #777777;
  stroke-width: 1;
}
/* @title >= 827581718.6 and < 1103442244.8 */
[POP_EST >= 827581718.6]
[POP_EST < 1103442244.8] {
  fill: #D7301F;
  fill-opacity: 1;
  stroke: #777777;
  stroke-width: 1;
}
/* @title >= 1103442244.8 and <= 1379302771 */
[POP_EST >= 1103442244.8]
[POP_EST <= 1379302771] {
  fill: #7F0000;
  fill-opacity: 1;
  stroke: #777777;
  stroke-width: 1;
}
```
